# Generated by Django 2.2 on 2020-06-08 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chambres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roommates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.TextField()),
                ('genre', models.IntegerField(choices=[(1, 'Garçons'), (2, 'Filles')], default=1)),
                ('valid', models.BooleanField(default=False)),
                ('third', models.BooleanField(default=False)),
                ('chambre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rommates_chambre', to='chambres.Chambre')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rommate1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rommate2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
