# Generated by Django 2.2 on 2020-06-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200608_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommates',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
