# Generated by Django 2.2 on 2020-06-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=4)),
                ('cite', models.IntegerField(choices=[(1, 'Cité 1'), (2, 'Cité 2'), (3, 'Cité 3')], default=1)),
                ('genre', models.IntegerField(choices=[(1, 'Garçons'), (2, 'Filles')], default=1)),
                ('is_taken', models.BooleanField(default=False)),
            ],
        ),
    ]
