# Generated by Django 2.2 on 2020-06-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chambres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambre',
            name='num',
            field=models.CharField(max_length=5),
        ),
    ]
