# Generated by Django 2.2 on 2020-06-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chambres', '0002_auto_20200608_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='chambre',
            name='name',
            field=models.CharField(default=' ', max_length=4),
            preserve_default=False,
        ),
    ]
